/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "dashboard.contacts.index": [],
    "dashboard.contacts.accoubt": [],
    "dashboard.file-manager.index": [],
    "dashboard.notes.index": [],
    "dashboard.scrumboard.index": [],
    "dashboard.todo.index": [],
    "dashboard.apps": [],
    "dashboard.chats": [],
    "dashboard.charts": [],
    "dashboard.mail": [],
    "dashboard.ecommerce.orders": [],
    "dashboard.ecommerce.products": [],
    "dashboard.ecommerce.products.edit": [],
    "dashboard.blog.posts": [],
    "dashboard.blog.posts.create": [],
    "dashboard.blog.posts.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "dashboard.blog.posts.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "dashboard.blog.categories": [],
    "dashboard.blog.tags": [],
    "dashboard.tasks": [],
    "dashboard.users": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "dashboard.coming-soon": [],
    "dashboard.03": [],
    "criteria.index": [],
    "criteria.create": [],
    "criteria.store": [],
    "criteria.show": [
        {
            "name": "criterion",
            "required": true
        }
    ],
    "criteria.edit": [
        {
            "name": "criterion",
            "required": true,
            "binding": "id"
        }
    ],
    "criteria.update": [
        {
            "name": "criterion",
            "required": true,
            "binding": "id"
        }
    ],
    "criteria.destroy": [
        {
            "name": "criterion",
            "required": true,
            "binding": "id"
        }
    ],
    "subcriteria.index": [],
    "subcriteria.create": [],
    "subcriteria.store": [],
    "subcriteria.show": [
        {
            "name": "subcriterion",
            "required": true
        }
    ],
    "subcriteria.edit": [
        {
            "name": "subcriterion",
            "required": true
        }
    ],
    "subcriteria.update": [
        {
            "name": "subcriterion",
            "required": true,
            "binding": "id"
        }
    ],
    "subcriteria.destroy": [
        {
            "name": "subcriterion",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
